version: '3'

networks:
  proxy:
    external: true	

services:

  mqtt:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
    deploy:
      placement:
        constraints:
          - node.role == worker
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.mqtt.rule=Host(`mqtt.home`)"
        - "traefik.http.routers.mqtt.entrypoints=forwarding"
        - "traefik.http.services.mqtt.loadbalancer.server.port=1883"
        - "traefik.docker.network=proxy"
    networks:
      - proxy


  server:
    image: korbier/rpi-jeedom
    ports:
      - "10008:80"
    volumes: 
      - /home/pi/volumes-shared/jeedom/html:/var/www/html
      - /home/pi/volumes-shared/jeedom/mysql:/var/lib/mysql     
    deploy: 
      placement:
        constraints:
          - node.role == worker
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.jeedom.rule=Host(`jeedom.home`)"
        - "traefik.http.routers.jeedom.entrypoints=web"
        - "traefik.http.services.jeedom.loadbalancer.server.port=80"
        - "traefik.docker.network=proxy"
    networks:
      - proxy

